### PR TITLE
Add sbt 1.0.0-RC2 support

### PR DESCRIPTION
**Pull request by rockjam**
This PR adds support for recent sbt 1.0.0-RC2 release

### CODE REVIEW

**Comment by rockjam** [comment]
Not sure that defining settings in `LibraryPlatform` is good idea, but it was the easiest way

**Comment by dwijnand** [comment]
Would be wonderful to have this accepted and a release (or prerelease/milestone release) for sbt 1.0. ❤️

**Comment by rockjam** [comment]
@pauldraper could you take a look at this?

**Review by joeycozza — APPROVED** [review]

**Comment by joeycozza** [comment]
Looks good. Will be cutting a release today.  Thanks for your help @rockjam

**Pull request merged**
