### PR TITLE
Improve version detection

### PR DESCRIPTION
**Pull request by leonardehrenfried**
I'm getting an error when trying to use scalafmt 1.3 with this plugin and I'm proposing a more flexible and future-proof way of determining the version.

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
Bump!

Is there a chance that this could be merged an released?

**Comment by jvican** [comment]
This is great. We're experiencing the same issue in sbt/zinc.
  
@pauldraper Is it possible to get this merged?

**Comment by jvican** [comment]
@joeycozza @pauldraper Can you either merge this or give someone else rights to merge and release these changes? @leonardehrenfried seems quite active.
  
If you don't have time for it, please let me know and I'll release my own version of this plugin to avoid bothering you.

**Comment by joeycozza** [comment]
Hey @jvican I have recently left lucidsoftware, and no longer have the rights for this repo. Sorry man.

I believe that @pauldraper wrote the check in that manner because there wasn't a guarantee that binary compatibility would be kept, as can be seen from the comments at the PR here https://github.com/lucidsoftware/neo-sbt-scalafmt/pull/36, but I'm not really sure that was his intention or not. 

Either way, sorry I can't help you guys out.

**Comment by jvican** [comment]
@joeycozza Thanks for the reply.

**Comment by pauldraper** [comment]
> I believe that @pauldraper wrote the check in that manner because there wasn't a guarantee that binary compatibility would be kept

Correct. At the time, the only 1.x releases were RC.

Now that we've hit scalafmt 1.0, it's reasonable to assume binary compatibility.

**Comment by jvican** [comment]
Thank you @pauldraper.

**Pull request merged**
