### PR TITLE
Fix #10: Cross-compile to sbt 1.0.0-M6

### LINKED ISSUE #10: Release plugin for sbt 1.0.0-M6
Last milestone for sbt 1.0 is out. We would like to upgrade the build of sbt, and since we're there depending on this plugin, we need `neo-sbt-scalafmt` released.
  
By the way, great job. The plugin is fantastic.

### PR DESCRIPTION
**Pull request by jvican**

### CODE REVIEW

**Comment by jvican** [comment]
Required changes are due to the usability checks. With the latest milestone, normal task evaluation is forced to be more static to avoid common pitfalls.

**Comment by jvican** [comment]
It seems CI is broken: https://travis-ci.org/lucidsoftware/neo-sbt-scalafmt/builds/241904364?utm_source=github_status&utm_medium=notification. The culprit is not this PR, but it also happens in the rest of the PRs in the queue.

**Comment by olafurpg** [comment]
It seems to be downloading metaconfig-core 0.3.2, which got broken by a mutated release on sonatype (see https://issues.sonatype.org/browse/OSSRH-31815 and https://github.com/scalameta/scalafmt/issues/943) The build should not depend on scalafmt 0.7.0-RC1, just 1.0.0-RC1, they're practically the same release, 0.7 was supposed to be 1.0.

**Comment by jvican** [comment]
@pauldraper can you have a look at this? I've tried to fix the aforementioned bug with Olaf's approach, but it doesn't seem to work for now. Still getting linking errors. This is weird... I've succeeded to publish locally and depend on it from 1.0.0-M6, but I have no idea why the CI is behaving like that. Maybe its cache is corrupted, too?

**Comment by pauldraper** [comment]
Weird. I cleared the caches and re-ran a previously successful build and it failed. https://travis-ci.org/lucidsoftware/neo-sbt-scalafmt/builds/240156063

I will look into this more.

**Comment by olafurpg** [comment]
metaconfig-core 0.3.2, which scalafmt 0.7.0-RC1 depends on, is still being resolved in the logs https://travis-ci.org/lucidsoftware/neo-sbt-scalafmt/builds/242550480#L577

That release got overwritten on Maven Central, what happens if you change https://github.com/lucidsoftware/neo-sbt-scalafmt/pull/11/files#diff-fdc3abdfd754eeb24090dbd90aeec2ceR22 ?

**Comment by pauldraper** [comment]
@olafurpg was correct that 0.7.0-RC1 no longer worked, but it was scalafmtVersion in neo-sbt-scalafmt/build.sbt that needed to be updated so scalafmt::test on neo-sbt-scalafmt passed, not the ScalafmtPlugin code.

Oh, the perils of self-hosting, or at least self-dependency. :/

Anyway, rebasing/merging master will fix the build. Scalafmt 1.0.x support was added in a different commit, so there are some conflicts. The original proposed changes should be fine.

**Comment by jvican** [comment]
Tests are passing @pauldraper. Everything's rebased and latest commit is removed. One question: shouldn't we remove 0.7.0-RC1 plugin support and add it for 1.0.0-RC1? If so, could you do it?
  
N.B. Note that because you are not pattern matching on 1.0.0 version inside the plugin, you're now showing a warning that says "unrecognised version".

**Comment by pauldraper** [comment]
Yep. Support for scalafmt 1.0.0-RC2 just added (sbt-scalafmt 1.1).

Since the scalafmt interface didn't change from 0.7, it still was working fine, but with the unpleasant warning you pointed out.

**Comment by jvican** [comment]
I cannot resolve sbt 1.1 from sbt 1.0.0-M6, even though it has hit Maven Central. What have you done to release the plugin?

**Comment by jvican** [comment]
```
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /data/rw/code/scala/zinc/project
[info] Updating {file:/data/rw/code/scala/zinc/project/}zinc-build...
[warn] 	module not found: com.lucidchart#sbt-scalafmt;1.1
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.lucidchart/sbt-scalafmt/scala_2.12/sbt_1.0.0-M6//1.1/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.lucidchart/sbt-scalafmt/scala_2.12/sbt_1.0.0-M6//1.1/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /home/jvican/.ivy2/local/com.lucidchart/sbt-scalafmt/scala_2.12/sbt_1.0.0-M6//1.1/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/lucidchart/sbt-scalafmt_2.12_1.0.0-M6/1.1/sbt-scalafmt-1.1.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /home/jvican/.sbt/preloaded/com.lucidchart/sbt-scalafmt/1.1/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////home/jvican/.sbt/preloaded/com/lucidchart/sbt-scalafmt_2.12_1.0.0-M6/1.1/sbt-scalafmt-1.1.pom
[info] :: loading settings :: url = jar:file:/home/jvican/.sbt/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-M6/ivy-2.3.0-sbt-a3314352b638afbf0dca19f127e8263ed6f898bd.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] :: loading settings :: url = jar:file:/home/jvican/.sbt/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-M6/ivy-2.3.0-sbt-a3314352b638afbf0dca19f127e8263ed6f898bd.jar!/org/apache/ivy/core/settings/ivysettings.xml
[info] :: loading settings :: url = jar:file:/home/jvican/.sbt/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-M6/ivy-2.3.0-sbt-a3314352b638afbf0dca19f127e8263ed6f898bd.jar!/org/apache/ivy/core/settings/ivysettings.xml
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.lucidchart#sbt-scalafmt;1.1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.lucidchart:sbt-scalafmt:1.1 (scalaVersion=2.12, sbtVersion=1.0.0-M6)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.lucidchart:sbt-scalafmt:1.1 (scalaVersion=2.12, sbtVersion=1.0.0-M6) (/data/rw/code/scala/zinc/project/plugins.sbt#L5-6)
[warn] 		  +- default:zinc-build:0.1-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0.0-M6)
```

**Comment by pauldraper** [comment]
Apologies. The scalafmt 1.0.0-R2 support (no warning) that you mentioned was added in 1.1.

This merge first went out in 1.2, which hadn't been released when you tried. (Though now, 1.6 is the one to use.)

**Comment by jvican** [comment]
Thanks for the heads up.

**Pull request merged**
